url: https://swreflections.uk
baseurl: 

# Site settings
title: Software Reflections
email: info@swreflections.uk
description: "Bespoke software development and consultancy."


# Team names, titles and social links
# people:
# - name: Rui Mourato
#   pic: 1
#   position: Full-Stack Engineer
#   social:
#     - title: twitter
#       url: #
#     - title: facebook
#       url: #
#     - title: stack-overflow
#       url: #

# - name: John Doe
#   pic: 2
#   position: Dev
#   social:
#     - title: twitter
#       url: #
#     - title: facebook
#       url: #
#     - title: linkedin
#       url: #

# Social networks usernames
# social:
#   - title: twitter
#     url: http://twitter.com/jekyllrb
#   - title: stack-overflow
#     url: http://stackoverflow.com/questions/tagged/jekyll
#   - title: github
#     url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
# address:
#   - line: 3481 Melrose Place
#   - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty